INSERT into players (player_name)values ('Lapsha');
INSERT into players (player_name) values ('Kukisha');
INSERT into players (player_name) values ('Suspents');
INSERT into players (player_name) values ('Druma');
INSERT into players (player_name)values ('｡  🎀  𝑀𝒾𝒸𝒽𝒶𝑒𝓁  🎀  ｡');
INSERT into players (player_name) values ('LoveLove');
INSERT into players (player_name) values ('Gregori');
INSERT into players (player_name) values ('Pumba');
INSERT into players (player_name) values ('Cocojamboo');
INSERT into players (player_name) values ('Anonymous228');
INSERT into players (player_name) values ('Janet');
INSERT into players (player_name) values ('Mr.P');
INSERT into players (player_name) values ('Mosquito');
INSERT into players (player_name) values ('Table');
INSERT into players (player_name) values ('Angelina');
INSERT into players (player_name) values ('Ramazano');
INSERT into players (player_name) values ('Vanloose');
INSERT into players (player_name) values ('Vantyz');


INSERT into matches (player1, player2, Winner)values (1,2,1);
INSERT into matches (player1, player2, Winner) values (2,3,3);
INSERT into matches (player1, player2, Winner) values (4,2,2);
INSERT into matches (player1, player2, Winner) values (1,4,1);
INSERT into matches (player1, player2, Winner)values (10,9,10);
INSERT into matches (player1, player2, Winner) values (8,9,8);
INSERT into matches (player1, player2, Winner) values (7,10,10);
INSERT into matches (player1, player2, Winner) values (6,8,8);
INSERT into matches (player1, player2, Winner) values (5,8,5);
INSERT into matches (player1, player2, Winner) values (5,10,10);
INSERT into matches (player1, player2, Winner) values (6,5,6);
INSERT into matches (player1, player2, Winner) values (11,12,12);
INSERT into matches (player1, player2, Winner) values (12,9,9);
INSERT into matches (player1, player2, Winner) values (18,17,18);
INSERT into matches (player1, player2, Winner) values (13,12,13);
INSERT into matches (player1, player2, Winner) values (14,15,15);
INSERT into matches (player1, player2, Winner) values (15,12,12);
INSERT into matches (player1, player2, Winner) values (16,5,5);
INSERT into matches (player1, player2, Winner) values (12,1,1);
INSERT into matches (player1, player2, Winner) values (18,12,12);
INSERT into matches (player1, player2, Winner) values (1,12,1);
